### ISSUE TITLE
Update BBC radio logos 

### ISSUE THREAD

**Issue by jontywilliamson** [njh/radiodns-uk#45]
Update the bbc radio logos to the new font

**Comment by njh** [comment]
The logos on this website all come directly from the broadcasters.
Once the BBC updates its logos, they will appear on radiodns.uk too.

Note that the new stations logos aren't on https://www.bbc.co.uk/sounds either yet...

**Comment by njh** [comment]
@jontywilliamson the BBC logos have now been updated

**Comment by jontywilliamson** [comment]
That is good

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
